project:
  type: website
  output-dir: docs

website:
  site-url: https://Clement-Poupelin.github.io/
  favicon: img/logo_univ_lille2.png
  title: Clément Poupelin
  navbar:
    background: light
    title: Clément Poupelin
    logo: img/logo_univ_lille_gros.png
    right:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
          - Open16S.qmd
      - publications.qmd
      - icon: info-circle-fill
        href: about.html
      - href: CV/CV.pdf
        text: CV
      - icon: github
        href: http://github.com/Clement-Poupelin
      - icon: gitlab
        href: http://forgemia.inra.fr/clement.poupelin
      - icon: instagram
        href: https://www.instagram.com/clement__poupelin
      - icon: linkedin
        href: http://www.linkedin.com/in/cl%C3%A9ment-poupelin-7675311a7/
      - icon: envelope
        href: mailto:clementjc.poupelin@gmail.com
  page-footer: 
    background: light
    left: Copyright 2025, Clément Poupelin
    right: This website is built with [Quarto](https://quarto.org/)

format:
  html:
    toc: true

execute:
  freeze: auto






# project:
#   type: website
#   output-dir: docs
#   
# website:
#   title: "Clément Poupelin"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - projects.qmd
#     tools:
#       - icon: instagram
#         href: https://twitter.com/
#       - icon: github
#         href: https://github.com/YOURUSERNAME/YOURREPO
#       - icon: gitlab
#         href: https://github.com/YOURUSERNAME/YOURREPO
#       - icon: linkdin
#         href: https://github.com/YOURUSERNAME/YOURREPO
#   page-footer:
#     right: "Built with [Quarto](https://quarto.org/)"
#     left: "&copy; Copyright 2023, YOUR NAME"
# 
# format:
#   html:
#     theme: cerulean
#     toc: true
# 
# editor: source

