---
title: ""
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(kableExtra)
identity_keys <- cell_spec(
  x = c(
  "Title", 
  "E-mail professionnal", 
  "E-mail personnal", 
  "Address", 
  "Academic status", 
  "Main field of expertise",
  "Unit // Team"
), format = "html", bold = TRUE)
identity_values <- c(
  "Ingeneer", 
  cell_spec("clement.poupelin@univ-lille.fr", format = "html", link = "mailto:clement.poupelin@univ-lille.fr"), 
  cell_spec("clementjc.poupelin@gmail.com", format = "html", link = "mailto:clementjc.poupelin@gmail.com"), 
  "Cité Scientifique / Building ESPRIT - desks S3.39/S3.41/S3.43 - Villeneuve d'Ascq, France<br>Campus Santé / Building Plateformes-Cancer - Lille, France<br>Campus Pasteur Lille / Building Calmette 4ème étage - Lille, France", 
  "Ingénieur d'étude", 
  "Statistic",
  cell_spec("Plateformes Lilloises en Biologie et Santé (PLBS) - UAR CNRS 2014 - US Inserm 41 // Plateforme Bilille Bioinformatique et Biostatistique de Lille", format = "html", link = "https://bilille.univ-lille.fr/")
)
tibble(
  keys = identity_keys, 
  values = identity_values, 
) %>% 
  kbl(
    format = "html", 
    booktabs = TRUE, 
    escape = FALSE, 
    col.names = NULL
  ) %>% 
  kable_styling(bootstrap_options = c("hover", "condensed"))
```


## Skills

- Analysis and mathematical modeling of large-scale datasets (Big Data)

- Time series modeling and forecasting

- Implementation of Bayesian techniques and machine learning methods

- Application of data science skills to microbial ecology

- Use of statistical methods for meta-analyses

- Research on microbiome network inference methods

## Course

After earning a Scientific Baccalaureate (BAC S SVT) with a Mathematics specialization, I pursued a [Bachelor's degree in Mathematics at Nantes University](https://sciences-techniques.univ-nantes.fr/formations/licences-generales/licence-de-mathematiques), followed by a [Master's in Statistical Engineering](https://www.math.sciences.univ-nantes.fr/master-IS), which I obtained with honors (mention bien). 

My interest in research grew through my final-year internship, leading to my first position as a research engineer at the [UR 1404 Applied Mathematics and Computer Science from Genome to Environment (MaIAGE)](https://maiage.inrae.fr/) unit of INRAE, located in Jouy-en-Josas within the Paris-Saclay research cluster.

I then joined the [Bilille platform](https://bilille.univ-lille.fr/) (Bioinformatics, biostatistics and bioanalysis) within the [UAR 2014 - US 41 PLBS](https://ums-plbs.univ-lille.fr/) unit at the University of Lille, working under an RHU-funded research program focused on neurodegenerative diseases. My primary objective is to identify biomarkers for amyotrophic lateral sclerosis (ALS).